apiVersion: v1
kind: Service
metadata:
  name: aks0-lfa  
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: lfa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lfa
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: lfa.96064fddcffb4f8fb419.northeurope.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: lfa
            port: 
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aks1-lfa  
spec:
  type: ClusterIP
  ports:
  - port: 5001
  selector:
    app: lfa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lfa
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: lfa1.96064fddcffb4f8fb419.northeurope.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: lfa
            port: 
              number: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: aks2-lfa  
spec:
  type: ClusterIP
  ports:
  - port: 5002
  selector:
    app: lfa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lfa
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: lfa2.96064fddcffb4f8fb419.northeurope.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: lfa
            port: 
              number: 5002