member:
  replicaCount: 1

  image:
    repository: filip8600/lfa
    pullPolicy: IfNotPresent
    tag: "latest"

  podAnnotations: {}

  podSecurityContext:
    runAsUser: 101

  securityContext:
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP
    port: 5081
  

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  averageCpuUtilization: 90
