member:
  replicaCount: 2
  image:
    repository: acrworkflow1669713859901.azurecr.io/image-workflow-1669713859901
    pullPolicy: Always
    tag: "always.replace.me"

  podAnnotations: {}

  podSecurityContext:
    runAsUser: 101

  securityContext:
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP
    port: 5000


hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  averageCpuUtilization: 90
